### ISSUE TITLE
split plugin add yum repo by url

### ISSUE THREAD

**Issue by TomasTomecek** [DBuildService/dock#108]
Since we are able to squash, there's pretty much no need for injecting yum calls inside dockerfile. Much nicer way will be to add repos with `ADD`, install packages and remove repos (`RUN rm /etc/yum.repos.d/*`) -- exactly what "add yum repo by url" plugin does. Therefore I think we should split the functionality of the plugin to two:

1. **fetch plugin**: downloads repo files from web
2. **add plugin**: hooks repos to build process by adding `ADD` and `RUN rm ...`

I'm not sure about the first one, how exactly should the plugin operate:
1. put repo configuration to `workflow.repos` object
2. **add** plugin will take everything from the `workflow.repos`, creates repo file out of it and adds instructions in dockerfile

or

1. **fetch** plugin downloads repo files, store them in image
2. **add** plugin will use downloaded files and also creates repo files from whatever is in `workflow.repos`

@twaugh what do you think?

**Comment by twaugh** [comment]
I'm not sure of the utility of splitting fetching from adding. I can see that it might be useful to make it into a more generic 'fetch, add, remove' operation, without assuming it needs to add fetched content to `/etc/yum.repos.d/`, though.

Do you mean that several plugins might want to use `fetch` separately, and then `add` would deal with them all at once? I'm trying to think of a use-case.

**Comment by TomasTomecek** [comment]
Right! My use case is that I want to use plugin which

 * will provide same functionality as plugin `inject_yum_repo`
 * can be used together with `koji` plugin

Essentially I want to take output of `koji` plugin and stuff that repo in dockerfile the same way `add_yum_repo_by_url` plugin does.

Does that make sense?

**Comment by twaugh** [comment]
I see, got it. So how about this?:

```
{
    'name': 'fetch',
    'args': {
        'files': {
            '/etc/yum.repos.d/repo1.repo': 'https://example.com/repo1.repo',
            '/etc/yum.repos.d/repo2.repo': 'https://example.com/repo2.repo'
        }
    }
},
{
    'name': 'add'
}
```
where the pre_fetch plugin simply populates `workflow.tmpconfig` with the filename:url dict entries.

**Comment by TomasTomecek** [comment]
so the koji plugin should store the repo file to the `workflow.tmpconfig`?

**Comment by twaugh** [comment]
Yes, that's what I'm thinking.

```python
self.workflow.tmpconfig['/etc/yum.repos.d/koji.repo'] = ...
```

**Comment by TomasTomecek** [comment]
So the value of that key in the dict will be content of the repo file?

**Comment by twaugh** [comment]
Oh, good point. Yes, let's do that. ;-)
```python
self.workflow.tmpconfig['/etc/yum.repos.d/koji.repo'] = b'[fedora]\nname=...'`
```

**Comment by TomasTomecek** [comment]
Sounds great! Will you have time to work on that? I really would like have this thing done this week (meaning, if you don't have time, I can take care of this tomorrow).

**Comment by TomasTomecek** [comment]
@adamruzicka since you are using `yum_inject` plugin: we are planning to change behavior of the plugin so by default it injects repos by doing `ADD repos/*` and `RUN rm /etc/yum.repos.d/*`. Since we are able to squash layers, we know that no leftovers from yum will be in final image (nor in any of its layers). You can get the former functionality by using switch `wrap_commands=True` (it's `False` by default). This patch also changes the way plugins pass yum repos: there's variable `files` now on workflow object:

```python
files["/etc/yum.repos.d/my.repo"] = "[my-repo]\nname=my-repo\n..."
```

I would like to merge this patch soon but certainly don't want break your workflow. Are there any concerns from your side?

**Comment by adamruzicka** [comment]
@TomasTomecek we were using ```yum_inject``` only in the early stages before we switched to subscription-manager, so you don't have to worry about breaking my workflow. 

I really like the way how injecting repos should work with this patch
