### ISSUE TITLE
new plugin: copy file/dir within build container to NFS share

### ISSUE THREAD

**Issue by TomasTomecek** [DBuildService/dock#120]
~~We need to import final image into koji. koji has its backend on NFS. We could possibly create a bindmount from the NFS on host to secrets dir and put the final built image inside this dir.~~

# ~~Previously proposed solution~~

1. ~~mount NFS inside secrets path on host:~~
```
/mnt/nfs/path` -> `/usr/share/rhel/secrets/something
```
2. ~~our docker does this automatically: it mounts `/usr/share/rhel/secrets` from host to `/run/secrets` in container~~
3. ~~finally, if we copy tarball to `/run/secrets/something` it could be propagated to NFS~~

# Current solution

Pre-req: build container has to have `/sbin/mount.nfs`

1. create directory for mountpoint: `/path`
2. mount the nfs share: `mount -t nfs -o nolock nfs:/export /path`
3. copy file to `/path`

Plugin's configuration

* nfs chain (`nfs:/export`)
* `-o` opts, `nolock` is required:
```
mount.nfs: rpc.statd is not running but is required for remote locking.
mount.nfs: Either use '-o nolock' to keep locks local, or start statd.
```
* path, where to copy the file

**Comment by jpopelka** [comment]
Well, I have the plugin (https://github.com/jpopelka/dock/commit/530146271fefeef2fba466c336416ae29fb99e41) and it does what's been requested, i.e. copies the built image tarball into `/run/secrets/built_images/`.

But it seems that the content of `/run/secrets/` is not propagated back to host, so it doesn't look like the way to solve this issue.

**Comment by TomasTomecek** [comment]
I was told today that the secrets patch is implemented via tmpfs and not as bind mounts. Therfore it can't work :/

**Comment by TomasTomecek** [comment]
I have finally figured out a solution to the problem, which is getting the tarball to NFS.

```bash
% docker run --rm -ti --privileged fedora:22 bash
[root@e40165809ef4 ~]# dnf install -y /sbin/mount.nfs
[root@e40165809ef4 ~]# mkdir /asd
[root@e40165809ef4 ~]# mount nfs:/export -o nolock -t nfs /asd
[root@e40165809ef4 ~]# cp -a image.tag /asd/path/
```

Could you please incorporate such functionality into the plugin? Am renaming this issue accordingly.

**Comment by jpopelka** [comment]
Nice

> docker run --rm -ti --privileged fedora:22 bash

Does it mean it'll be possible to run the plugin only with `--method privileged` ?

> dnf install -y /sbin/mount.nfs

Will the `nfs-utils` be part of build-image or should I install it with the plugin ?

> mkdir /asd

Perhaps `/tmp/asd/` ?

BTW, I have a course these 2 days (Mo, Tue), so I'll take a look this evening if nobody does it first.

**Comment by TomasTomecek** [comment]
> Does it mean it'll be possible to run the plugin only with --method privileged ?

Hmmm, good point. You need to have [CAP_SYS_ADMIN](http://man7.org/linux/man-pages/man7/capabilities.7.html) to be able to mount. Meaning, you either have to specify that cap when creating container or running container as `--privileged`. It looks like we might start looking into dependencies of plugins.

> Will the nfs-utils be part of build-image or should I install it with the plugin ?

It should definitely be part of build image: I would prefer creating subpackage with plugin and setting `Requires: nfs-utils` there.

> Perhaps /tmp/asd/ ?

This is a tricky one. `/tmp` is probably read-only tmpfs, not sure how that stuff works: if we can put write mountpoint there.

**Comment by pbabinca** [comment]
I guess the name will be as part of tar_metadata: #122. After you implement this functionality please create API in osbs similarly to https://github.com/DBuildService/osbs/issues/111

**Comment by mikem23** [comment]
If this is intended to get data into the file store of a Koji instance, then you should not rely on having write access to that share. It would be more correct to upload through kojihub, but perhaps I am missing context.

**Comment by pbabinca** [comment]
To satisfy @mikem23 concerns we found alternative solution. From dock point of view there won't be any change - it will copy image to mounted NFS share. The difference will be in the machine configuration. NFS share will be on the builder machine. In the architecture where Koji is involved the directory where dock writes images will be available via httpd.
