### ISSUE TITLE
Get metadata for a container image

### ISSUE THREAD

**Issue by pbabinca** [DBuildService/dock#122]
Get following info from the squashed tar.gz:
 - size
 - hash of the file
 - specify used hash `sha256`

and return it similarly as `rpm-packages` after the build.

**Comment by TomasTomecek** [comment]
More thorough description:

After we move to pulp, we will be pushing tarballs, not docker images (via docker API). Koji will also be interested in the tarballs and it needs some [metadata](https://github.com/release-engineering/koji-containerbuild/commit/6ec30da4dcd15bd58d61da627042dee904e1ac9c) about the tarball. Hence this issue.

Therefore this is a follow up to #121. The way this should be implemented is to take the tarball from #121 and compute md5 sum and size of the tarball. The information should be then stored inside openshift using plugin https://github.com/DBuildService/dock/blob/master/dock/plugins/post_store_metadata_in_osv3.py. The structure could be

```
"tar_metadata": {
  "checksum": "...",
  "size": "123",
}
```

and then put relevant methods to [BuildRequest](https://github.com/DBuildService/osbs/blob/master/osbs/build/build_response.py#L91) in osbs-client.
