### ISSUE TITLE
store actual dockerfile in metada, not DockerfileParser object

### ISSUE THREAD

**Issue by TomasTomecek** [DBuildService/dock#139]
when I do `osbs get-build`, this is what I get:
```
DOCKERFILE

<dock.util.DockerfileParser object at 0x2b807d0>

```
@jpopelka 
Jirko, can you look into it please?

**Comment by jpopelka** [comment]
@TomasTomecek I think you need https://github.com/DBuildService/dock/commit/ba5f27d63ae3e6407943303bfbe52098e7fa0d20 (at least the first part)

**Comment by jpopelka** [comment]
Added https://github.com/DBuildService/dock/commit/9e875c5eaed90ab39334633a6cf2c94da1a55feb to avoid this in future. Closing at it's already been fixed.

**Comment by TomasTomecek** [comment]
:+1:
