### ISSUE TITLE
Allow for custom location of pulp secrets

### ISSUE THREAD

**Issue by twaugh** [DBuildService/dock#151]
The `post_push_to_pulp` plugin should allow a custom location for pulp secrets in order to work around https://github.com/openshift/origin/issues/2921.

My proposal is simply to fall back to `/etc/pki/pulp/` (hard-coded) if `SOURCE_SECRET_PATH` is not set in the environment. In that way, we can simply ~~use the `prod` build type, rather than the `prod-with-secret` build type,~~ not set `sourceSecretName` in the build JSON to force the use of that path.

**Comment by twaugh** [comment]
@TomasTomecek, see what you think.

**Comment by TomasTomecek** [comment]
@twaugh 
wow, that was quick!

Could you please add there some logging about from what place the certs are being fetched? Other than that, it's LGTM. (once it's done, we should create some docs for the plugin)

**Comment by twaugh** [comment]
@TomasTomecek, done.

**Comment by twaugh** [comment]
Looking at this again, it will mean changing osbs so that it only sets `sourceSecretName` if it is already present in the build JSON.

I think I'd better change this to just be a plugin parameter, `pulp_secret_path`.

**Comment by twaugh** [comment]
Fixed on `dock-pulp` branch.
