### ISSUE TITLE
Fix docs for add_yum_repo_by_url plugin

### ISSUE THREAD

**Issue by goldmann** [DBuildService/dock#172]
Currently it's necessary to add also `inject_yum_repo` to make the `add_yum_repo_by_url` plugin work, but it's not mentioned anywhere. Moreover, the plugin description suggests that to add the repo file you need to only enable this plugin.

In fact the name of the plugin is wrong too. It does not add the repo, but it only fetches that file.

/cc @bkabrda

**Comment by twaugh** [comment]
The name of the plugin reflects the fact that the repo is added to the set of repos the `inject_yum_repo` plugin injects.
