### ISSUE TITLE
dockerfile parser: understand label syntax "x y"

### ISSUE THREAD

**Issue by TomasTomecek** [DBuildService/dock#181]
this is what docker does:
```
LABEL x y
```

```
"Labels": {
    "x": "y"
},
```

**Comment by jpopelka** [comment]
Yes, that's a 'old' variant,
https://github.com/docker/docker/blob/master/builder/parser/line_parsers.go#L49
which the Dockerfile Reference doesn't even mention
https://docs.docker.com/reference/builder/#label

**Comment by twaugh** [comment]
Fixed via #180.
