### ISSUE TITLE
handle 'library' namespace

### ISSUE THREAD

**Issue by TomasTomecek** [DBuildService/dock#45]
when tagging, handle 'library' namespace correctly -- it is implicit namespace (if an image doesn't have any namespace, its namespace is 'library')

**Comment by TomasTomecek** [comment]
Looks like that issue is in `get_image_info_by_image_name`:
```
In [1]: from dock.core import DockerTasker                                                                                                                                                    
In [2]: t = DockerTasker() 
In [3]: t.get_image_info_by_image_name("fedora", "library")
Out[3]: []
```
`docker` behavior is the same:
```
$ docker images library/fedora                                                                                                                                
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
```
dock uses that method to get id of built image: http://fpaste.org/204721/42772035/
We need to teach that method operate with `library` namespace.

**Comment by jpopelka** [comment]
The 'docker images library/fedora' not listing any images seems like a docker issue to me, so I filed
https://github.com/docker/docker/issues/11955

**Comment by TomasTomecek** [comment]
Works great! Thanks!

**Comment by jpopelka** [comment]
One more fix https://github.com/DBuildService/dock/commit/2a4f2db6af2a59cb081e8fb1ccd263a7f16b8d05
