### ISSUE TITLE
tests_for_image plugin crashes with TypeError

### ISSUE THREAD

**Issue by TomasTomecek** [DBuildService/dock#46]
```python
File "lib/python2.7/site-packages/dock/plugins/prepub_tests_for_image.py", line 53, in __init__
   super(ImageTestPlugin, self).__init__(tasker, workflow)
TypeError: must be type, not None
```

Looks like that `ImageTestPlugin` is None (waaat?)

Reproducer:

https://gist.github.com/l-d-j/ab25eff16022053d615b
`ssh && su - jenkins`
build image `https://github.com/l-d-j/wildfly-test`

**Comment by l-d-j** [comment]
Strange is that even PrePublishPlugin (parent of ImageTestPlugin) is None. But only in constructor, If I print it right after importing it is resolved correctly.

**Comment by l-d-j** [comment]
Also I've tried to run different plugin (inject_yum_repo) and result is same.

**Comment by TomasTomecek** [comment]
This thing could be a fix: https://github.com/DBuildService/dock/commit/ea342099c257a15f062589f42c0810d232ad74fb

**Comment by TomasTomecek** [comment]
and this https://github.com/DBuildService/dock/commit/19466afa17562845a414f09f8c2a6ee8fb80d76f
