### ISSUE TITLE
merge --method here into inside-build and rename inside-build to local-build

### ISSUE THREAD

**Issue by TomasTomecek** [DBuildService/dock#59]
* [ ] merge `--method here` into `inside-build` -- these are very similar
 * [ ] we might need to create/update input plugin for this
* [ ] rename `inside-build` to `local-build` -- not very important, but `local-build` might be more clear

**Comment by jpopelka** [comment]
Duplicate of #85

**Comment by TomasTomecek** [comment]
good catch
