### ISSUE TITLE
Use correct refs to clone repo

### ISSUE THREAD

**Issue by goldmann** [DBuildService/dock#68]
Currently when you clone a git repository to get the files to build, you get all the refs with it. This makes it very slow, since *in all cases* you are not interested in all the refs, but only in the specified branch (most probably master), so `+refs/heads/master:refs/remotes/origin/master` should be used only.

This bug makes it slower and slower to build our images. It currently takes 1.5 minute (sic!) to checkout the repository, whereas with proper refs this takes 2 seconds.

**Comment by TomasTomecek** [comment]
> 1.5 minute

oh boy, what's in your git repos?

can take a look if gitpython supports that

**Comment by goldmann** [comment]
We use gerrit and it pull all our changes before finally downloading one branch.

**Comment by TomasTomecek** [comment]
Aha. Checked `man git-clone` and didn't find any option for cloning specific ref. Will need to investigate more.

**Comment by goldmann** [comment]
Try with `git init`, then configure remotes and refs.

**Comment by TomasTomecek** [comment]
here's the solution to the problem:

http://stackoverflow.com/a/4568323/909579
