### ISSUE TITLE
improve yum workflow

### ISSUE THREAD

**Issue by TomasTomecek** [DBuildService/dock#83]
When #82 is in place, we finally don't need to wrap `yum` calls with `printf ... >/etc/yum.repos.d/...`. I think we should improve the workflow to:

1. Add instruction after `FROM`/`MAINTAINER`:
 * either `ADD *.repo /etc/yum.repos.d/`
 * or `RUN wget -O /etc/yum.repos.d/ http://.../*.repo`
2. maintain yum cache and metadata during during build -- meaning, not interfering with present `RUN.*yum.*` calls
3. Add instruction at the end of dockerfile which erases all downloaded yum repos

After the final image is squashed, no build artifacts will leak.

**Comment by twaugh** [comment]
`ADD https://.../*.repo /etc/yum.repos.d/` was another idea, but it doesn't support authentication.

The current solution I have is to go with

```
RUN wget -O '/etc/yum.repos.d/repo1.repo' http://.../repo1.repo
```

after `FROM`/`MAINTAINER`, and

```
RUN rm -f '/etc/yum.repos.d/repo1.repo' ...
```

at the very end.

**Comment by twaugh** [comment]
Looking at other plugins, maybe it should put the `RUN rm -f` line before any `CMD` line it sees?

**Comment by TomasTomecek** [comment]
> maybe it should put the `RUN rm -f` line before any `CMD` line it sees?

Indeed. It shouldn't be much of a problem even if last instruction was the `rm -rf` call. Also, `ENTRYPOINT

**Comment by twaugh** [comment]
I've updated it to use `rm` before `CMD` / `ENTRYPOINT` / EOF. Still uses wget at the moment.

**Comment by twaugh** [comment]
OK, new commit using `ADD` instead. Think it's better?

**Comment by TomasTomecek** [comment]
Looks great! Let's give it a go.
